### DISCUSSION TITLE
Merging datasource with optional file

### DISCUSSION THREAD

**Discussion by m4rcs** [hairyhenderson/gomplate#1129] [Q&A] [answered]
I'm trying to merge default config files with optional config overrides like in the example. But I can't figure it out.

Can someone give me a hint how to solve it?

##  Example 
Directory structure: 
```
.
├── config
│   ├── common.yml
│   └── ...
├── defaults
│   ├── common.yml
│   ├── database.yml
│   └── ...
├── gomplate.yml
└── templates
    └── config.yml.tpl
```

`./config/common.yml`
```
timezone: "Europe/Berlin"
```

`./defaults/common.yml`
```
timezone: "America/Anchorage"
```

`./defaults/database.yml`
```
host: "localhost"
```

`./gomplate.yml`
```
inputDir: "templates/"
outputMap: |
  {{ .in | strings.ReplaceAll ".tpl" "" }}

datasources:
  common:
    url: "merge:./config/common.yml|./defaults/common.yml"
  database:
    url: "merge:./config/database.yml|./defaults/database.yml"
```

`./templates/config.yml.tpl`
```
common:
  timezone: "{{ (ds "common").timezone }}"
database:
  host: "{{ (ds "database").host }}"
```

Run `gomplate --config ./gomplate.yml`

Expected `./config.yml`

```
common:
  timezone: "Europe/Berlin"
database:
  host: "localhost"
```

Example as Zip: [example.zip](https://github.com/hairyhenderson/gomplate/files/6327533/example.zip)
