### DISCUSSION TITLE
nil coalescing ?

### DISCUSSION THREAD

**Discussion by daniel-torok** [hairyhenderson/gomplate#1175] [Q&A] [answered]
Can we do nil coalescing?

For example I have the following template:

```yaml
{{ $ds := datasource "ds" }}
foo:
  bar: {{ $ds.nonExisting | coalesce 1 }}
```

With `nonExisting: 2` in `ds` it would produce `bar: 2`.
Without `nonExisting` in `ds` it would produce `bar: 1`.

**Comment by hairyhenderson** [comment, marked as answer]
_(I've moved this to a discussion, as this isn't an issue so much as a question)_

@daniel-torok There is a way to accomplish this, though not in a way that's quite so compact. This can, however, be accomplished with an `if` condition.

One issue is that if you try to reference a missing key, gomplate will error - this is by design as gomplate treats missing keys as errors (see #310 for some discussion on this). To avoid this, you'll want to use [`has`](https://docs.gomplate.ca/functions/coll/#coll-has).

Here's an example:

```yaml
{{ $ds := datasource "ds" }}
foo:
  bar: {{ if has $ds "nonExisting" }}{{ $ds.nonExisting }}{{ else }}1{{end}}
```

Alternately, if the key _does_ exist, but you want to test whether it's false, you could look at the [`ternary`](https://docs.gomplate.ca/functions/test/#test-ternary) function. However in that case, IMO just using `if` would be more readable anyway.
