### DISCUSSION TITLE
Appending a string in already created yaml block

### DISCUSSION THREAD

**Discussion by infa-mseelam** [hairyhenderson/gomplate#1375] [Q&A]
input.yaml
```
cluster:  
    blueprint:
      name: bp1
      configs:
        - be: be1
           bu:  bu1
           namespace:
             - ns1
             - ns2
           productIamRoles:
             - role1
             - role2
        - be: be2
           bu: bu2
           namespace:
             - ns4
           productIamRoles:
             - role1
             - role5
```

Code for templatezation 

```
{{ if (index (datasource "input").cluster.blueprint "configs") }}    
{{- $clength := len (datasource "input").cluster.blueprint.configs }}
{{ if (gt $clength 0) }}
{{- range $index, $ele := (datasource "input").cluster.blueprint.configs }}
{{ if (index ($ele) "productIamRoles") }}
{{- range $index1, $ele1 := $ele.productIamRoles }}
 - groups:
    rolearn: arn:aws:iam::{{ index (datasource "accounts") $env }}:role/{{ $ele1 }}
       - {{ $ele.be }}-{{ $ele.bu }}-group
{{ end }}{{ end}}{{ end }}{{ end }}{{ end }}
```

Following is the current output with the above template. Note that " rolearn: role/role1" is repeated twice.
```
- groups:
  rolearn: role/role1
    - be1-bu1-group
- groups:
  rolearn: role/role2
    - be1-bu1-group
- groups:
  rolearn: role/role1
    - be2-bu2-group
- groups:
  rolearn: role/role5
    - be2-bu2-group

```

I need the following output " rolearn: role/role1" should have two entries 
```
- groups:
    rolearn::role/role1
      - be1-bu1-group
      - be2-bu2-group
- groups:
    rolearn: role/role2
      - be1-bu1-group
- groups:
    rolearn: role/role5
      - be2-bu2-group
```
