### DISCUSSION TITLE
Encoding a template

### DISCUSSION THREAD

**Discussion by cschmatzler** [hairyhenderson/gomplate#1455] [Q&A] [answered]
Hi!

I am trying to use gomplate for Kubernetes secrets, and as such need to encode values.
For one of my deployments, I need a secrets file mounted, which means I have the file as a template which then needs to be encoded.

So far, I've tried
```
apiVersion: v1
kind: Secret
metadata:
  name: synapse-config
  namespace: medium-place
data:
  config.yaml: {{ base64.Encode template "config" . }}
  
{{ define "config" }}
  server_name: {{ .Env.SERVER_NAME }}
  db_pass: {{ .Env.DB_PASS }}
  ....
{{ end }}
```
which results in a `unexpected <template> in parenthesized pipeline`.
Using the pipe syntax instead, `template "config" . | base64.Encode`, it encodes the dot as a string and passes that as parameter to the template instead of rendering the template and then encoding it.
Adding parenthesis doesn't seem to work.

Is there any way to accomplish this? 
Cheers
