### DISCUSSION TITLE
Self referencing templates.

### DISCUSSION THREAD

**Discussion by blmhemu** [hairyhenderson/gomplate#1636] [Q&A] [answered]
I have a single yaml in which is both the datasource and the target. As a very simple example, consider this.

```
key1: val1
key2: val2
key3:
  key4: val4
key5: |
  1 - {{ key1 }}
  2 - {{ key2 }}
  3.4 - {{ key3.key4 }}
```

Is such self-referencing datasource and target possible ? If so how do I do it ? Thanks 🙏

**Comment by hairyhenderson** [comment, marked as answer]
Hi @blmhemu - this is possible with some slight modification.

`foo.yaml`:
```yaml
key1: val1
key2: val2
key3:
  key4: val4
key5: |
  1 - {{ .key1 }}
  2 - {{ .key2 }}
  3.4 - {{ .key3.key4 }}
```

```console
$ gomplate -c .=foo.yaml -f foo.yaml
key1: val1
key2: val2
key3:
  key4: val4
key5: |
  1 - val1
  2 - val2
  3.4 - val4
```

This uses the `foo.yaml` file as both a datasource (used as the default [context](https://docs.gomplate.ca/syntax/#the-context)) and the template.

This works because the file is valid YAML before being processed.

Hope this helps!
