### DISCUSSION TITLE
Accessing values of Maps nested in an array

### DISCUSSION THREAD

**Discussion by Kalimero66** [hairyhenderson/gomplate#1722] [General]
Bonjour,
I'm stuck with a simple problem when trying to use gomplate on Helmfile input and I was wondering if someone can help.
My datasource file is a typical Helmfile input as follow: 

```yaml
environments: 
  envA:
    values: 
    - myMap1:
        k1: v1
        k2: v2
    - myMap2:
        k3: v3
        k4: v4
    - myMap3:
        k5: v3
        k6: v4
```
Is it possible to access `k4` value (.ie `v4`) in one line ? 
I know I could potentially could just convert `values` into a map of maps instead but there must be a better way with `gomplate` that I'm just not seeing.

Here are my files if anyone interested.

.gomplate.yaml:
```yaml
# Put the input files here
datasources: 
  env: 
    url: ./ds.yaml
# Put the template files here
inputFiles:
  - ./in.yaml.gotmpl
```

ds.yaml: 
```yaml
environments: 
  envA:
    values: 
    - myMap1:
        k1: v1
        k2: v2
    - myMap2:
        k3: v3
        k4: v4
    - myMap3:
        k5: v3
        k6: v4
```

`values` is an array of Maps , I guess I need to first find the index of `myMap2` in `values` before accessing `k4`.
As I have many (30+) Maps under `values`, I use a nested template to find the index of the map in the array but I find it overkilled (and I haven't to cover any corner case yet). Like I said there must be a better way. 

in.yaml.gotmpl:
```go
{{- $findMapIndex := `
{{- $k   := .key -}}
{{- range $idx, $val := .list -}}
  {{- if coll.Has $val $k -}}
    {{- printf "%d" $idx -}}
    {{- break -}}
  {{- end -}}
{{- end -}}
` -}}
{{- $envName     := (index (keys (ds "env").environments)  0) }}
{{- $env         := (index  (ds "env").environments $envName) }}
{{- $values      := (index $env "values") }}
 
{{- $dict := coll.Dict "key" "myMap2" "list" $values }}
{{- $i := conv.ToInt (tpl $findMapIndex $dict) }}
{{ printf "Value for k4 is:  %s" (index $values $i).myMap2.k4 }}

{{- $dict := coll.Dict "key" "myMap1" "list" $values }}
{{- $j := conv.ToInt (tpl $findMapIndex $dict) }}
{{ printf "Value for k1 is:  %s" (index $values $j).myMap1.k1 }}
```

```bash
->  gomplate --config .gomplate.yaml
Value for k4 is:  v4
Value for k1 is:  v1

```
