### DISCUSSION TITLE
Question: How can I do a different action if it is the last iteration of a loop

### DISCUSSION THREAD

**Discussion by loque1** [hairyhenderson/gomplate#1753] [Q&A] [answered]
This is less of an issue but more of a question
I have some yaml : 
```yaml
port_mappings:
   - test1:
      container_port: 8080
      protocol: "tcp"
      app_protocol: "http2"
   - test2:
      container_port: 9090
      protocol: "udp"
      app_protocol: "http"
```
This is passed into a template : 
```
{{ if has .config "port_mappings" }}
      "portMappings": [
      {{ range $key, $port_map := .config.port_mappings  }}
        {{ range $key, $value := $port_map  }}
        {
          "containerPort": {{ if has $value "container_port" }}{{ $value.container_port }}{{ else }}80{{end}},
          "protocol": "{{ if has $value "protocol" }}{{ $value.protocol }}{{ else }}tcp{{end}}",
          "appProtocol": "{{ if has $value "app_protocol" }}{{ $value.app_protocol }}{{ else }}http{{end}}"
        },
        {{ end }}
      {{ end }}
      ],
      {{ end }}
```
I want the last iteration not to add the "," so the rendered template is a valid json array like : 
```json
"portMappings": [
        {
          "containerPort": 8080,
          "protocol": "tcp",
          "appProtocol": "http2"
        },
        {
          "containerPort": 9090,
          "protocol": "udp",
          "appProtocol": "http"
        }
      ],
```
In other templating options there is built in $last signal that one can use. I can not find this type of option on how to do this. 
Is there a way I can construct this type of approach ?

Thanks for the all the incredible work on the tool.
