### DISCUSSION TITLE
How to loop list in a Yaml data source

### DISCUSSION THREAD

**Discussion by ffsetit** [hairyhenderson/gomplate#1845] [Q&A] [answered]
I have a need to generate multiple output files based on a single template. The key is a list defined in a yaml datasource
```
root:  
  region:
    primary: us-east1
      abbr: use1
    secondary: us-central1
      abbr: usc1
```

I have the file put working using the temp.Exec and file.Write functions (using a simple math.Seq), however i am currently unable to loop based on the regions from the datasource.
I've tried multiple versions including
```
{{ $regions := (ds "config").root.region }}
{{- range $region := $regions -}}
```

No matter what i try i get a template rendering error `mapping values are not allowed in this context`

**Comment by hairyhenderson** [comment, marked as answer]
Hi @ffsetit, that error is a YAML parsing error. YAML like this is invalid:

```yaml
primary: us-east1
  abbr: use1
```

The problem is that it's interpreting `us-east1` as a scalar (string) value for the key `primary`, but it seems you're _also_ trying to assign an object value (`abbr: use1`).

You'll need to fix the YAML first. I would suggest something like:

```yaml
primary:
  name: us-east1
  abbr: use1
```
