### DISCUSSION TITLE
Can't get templates to work in the gomplate.yml config

### DISCUSSION THREAD

**Discussion by NiceGuyIT** [hairyhenderson/gomplate#1996] [Q&A]
I can't seem to get `templates` working in the `gomplate.yml` config. First the files.

`/tmp/gomplate/t1.tmpl`
```text
Content of template one!
```

`/tmp/gomplate/t2.tmpl`
```text
Content of template 2!
```

`/tmp/gomplate/gomplate.yml`
```yml
templates:
  t1:
    url: file:///tmp/gomplate/t1.tmpl
  t2:
    url: file:///tmp/gomplate/t2.tmpl
```

It works if the templates are specified on the command line.
```bash
$ gomplate --template t1=file:///tmp/gomplate/t1.tmpl --template t2=file:///tmp/gomplate/t2.tmpl --in "Template 1: {{ template \"t1\" }}Template 2: {{ template \"t2\" }}"
Template 1: Content of template one!
Template 2: Content of template 2!
```

According to the docs[1], specifying the templates in a gomplate config should do the same. Unfortunately there is no output.
```bash
$ gomplate --config gomplate.yml --in "Template 1: {{ template \"t1\" }}Template 2: {{ template \"t2\" }}"
```

Specifying the `in` template inside the gomplate config doesn't work either. Removing the `templates` from the config makes `in` work leading me to think something is wrong with specifying `templates` in the config.
```yml
templates:
  t1:
    url: file:///tmp/gomplate/t1.tmpl
  t2:
    url: file:///tmp/gomplate/t2.tmpl

in: 'Template 1: {{ template "t1" }}Template 2: {{ template "t2" }}'
```

```bash
gomplate --config gomplate.yml
```

Am I misunderstanding how templates work in the config?

    gomplate version 3.11.7
    openSUSE Leap 15.5

[1] https://docs.gomplate.ca/config/#templates
