### DISCUSSION TITLE
Process datasources as templates before the final template

### DISCUSSION THREAD

**Discussion by tiawl** [hairyhenderson/gomplate#2151] [Q&A] [answered]
Hi,

I'm currently using the 3.11.7 version for homemade scripts. I am using it with some YAML datasources. I am facing a recurrent issue and maybe I am missing something in the documentation.
Because I am not so proud of my issue title I think that explaining it with an exemple is a better idea.

Suppose I have this YAML datasource:

```yaml
---
# awesome.yaml

my_awesome_map:
  first: 'this string is awesome'
  second: '{{ (datasource "awesome").my_awesome_map.first }}ly awesome'

...
```

when using this command line:

```
gomplate --datasource awesome=awesome.yaml --in '{{ (datasource "awesome").my_awesome_map.second }}'
```

It is printing:

```
{{ (datasource "awesome").my_awesome_map.first }}ly awesome
```

Which is indeniably correct.
However what I am expecting is:

```
this string is awesomely awesome
```

Currently, the solution I have is to use gomplate to resolve the awesome.yaml file with itself as datasource before. But I have to repeat this operation for each dependencies in my datasources.

Does it exist a way to make gomplate prints the result I am expecting with a unique execution ? If not, do you think it is something that we can see in the gomplate roadmap?

Thank you for this awesome tool.

**Comment by hairyhenderson** [comment]
@tiawl Thanks for filing this - I've converted this to a discussion topic since it's neither a bug report nor a feature request.

What you're looking for is nested templates - see the docs:

- https://docs.gomplate.ca/usage/#--template-t
- https://docs.gomplate.ca/config/#templates

I think that'll answer your question, but let me know if you have any more questions around how these work.

**Reply by tiawl** [reply]
Thank you for your answer. I give a try to the template option. It works for the example I mentioned. Unfortunately if I add a little bit of complexity it does not.

Here the datasource:
```yaml
---
# awesome.yaml

my_awesome_map:
  first: 'this string is awesome'
  second: '{{ (datasource "awesome").my_awesome_map.first }}ly awesome'
  third: '{{ (datasource "awesome").my_awesome_map.second }}ly awesome'

...
```

The command line:

```bash
gomplate --datasource 'awesome=awesome.yaml' --template 'awesome=awesome.yaml' --in '{{ template "awesome" }}'
```

And the result:

```yaml
---
# awesome.yaml

my_awesome_map:
  first: 'this string is awesome'
  second: 'this string is awesomely awesome'
  third: '{{ (datasource "awesome").my_awesome_map.first }}ly awesomely awesome'

...
```

For the last line I am expecting this:
```yaml
  third: 'this string is awesomely awesomely awesome'
```

How can I solve the template without executing gomplate several times ?

**Reply by tiawl** [reply]
In addition the `--template` option does not seem to work with environment variables:

The template:

```yaml
---
# user.yaml

my_map:
  user: 'My user is: {{ .Env.USER }}'

...
```

The command line:
```bash
export USER='banana'; gomplate --template user=user.yaml --in '{{ template "user" }}'
```

The output:
```yaml
---
# user.yaml

my_map:
  user: 'My user is: {"level":"error","error":"failed to render template <arg>: template: user:5:28: executing \"user\" at <.Env.USER>: nil data; no entry for key \"Env\"","time":"2024-06-29T08:34:58Z"}
```
