### ISSUE TITLE
Removing comments

### ISSUE THREAD

**Issue by jjangga0214** [hairyhenderson/gomplate#1026]
Hi!

In some rare cases, removing comments(e.g. `#` in yaml) automatically is needed.

What if `gomplate` provides such a feature?

Thanks!

**Comment by hairyhenderson** [comment]
Hi @jjangga0214 - thanks for logging this.

I think this is something that [`regexp.Replace`](https://docs.gomplate.ca/functions/regexp/#regexp-replace) could accomplish.

If you're dealing with YAML, though, is it a data source? If so, comments aren't preserved so you could simply output it with [`toYAML`](https://docs.gomplate.ca/functions/data/#data-toyaml):

_test.yaml:_
```yaml
# single-line comment
foo:
- bar # trailing comment
- baz:
    # indented comment
    qux: true
```

```console
$ gomplate -c test=./test.yaml -i '{{ . | toYAML }}'
test:
  foo:
    - bar
    - baz:
        qux: true
```
