### ISSUE TITLE
nil coalescing ?

### ISSUE THREAD

**Issue by daniel-torok** [hairyhenderson/gomplate#1173]
Can we do nil coalescing?

For example I have the following template:

```yaml
{{ $ds := datasource "ds" }}
foo:
  bar: {{ $ds.nonExisting | coalesce 1 }}
```

With `nonExisting: 2` in `ds` it would produce `bar: 2`.
Without `nonExisting` in `ds` it would produce `bar: 1`.
