### ISSUE TITLE
How to include yaml subpath

### ISSUE THREAD

**Issue by Davincible** [hairyhenderson/gomplate#1451]
I am trying to take a subpath of yaml in my config, and include it unparsed my output.

Goal:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-one
  labels:
    app: one 
    two: hi there

---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-two
```

config:
```yaml
---
dev:
  namespaces:
    - name: ns-one
      labels:
        name: hi there
        app: one
    - name: ns-two

```

I tried the include and `data.ToYAML` but couldn't get it included or parsed right.
Any idea how to achieve this?
