### ISSUE TITLE
Passing key=value pairs as datasource does not work

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [hairyhenderson/gomplate#1494]
I have the following template file

```
apiVersion: v2
description: Helm chart for the {{ .Values.Name }} microservice
name: {{ .Name }}
version: {{ .Chartversion }}
appVersion: {{ .Chartversion }}
keywords:
  {{- range .Keywords}}
  - {{ . -}}
  {{ end }}
sources:
  {{- range .Sources}}
  - {{ . -}}
  {{ end }}
dependencies:
  - name: dependency
    version: ~0.1.1
    repository: "file://../../../dependency/"
```

When I try to render it passing command line key value pairs as datasource(s) it does not seem to work

```
▶ gomplate -f templates/Chart.tmpl -d Name=fo
apiVersion: v2
description: Helm chart for the 11:18:20 ERR  error="failed to render template templates/Chart.tmpl: template: templates/Chart.tmpl:2:35: executing \"templates/Chart.tmpl\" at <.Name>: map has no entry for key \"Name\""
```
