### ISSUE TITLE
Problem with path in checksums file

### ISSUE THREAD

**Issue by tamere-allo-peter** [hairyhenderson/gomplate#1513]
Trying to install the latest binary release from Ansible while checking the checksum using Ansible's `get_url` method, I've encountered the problem that the binary path in the sha256 checksums file is prefixed with `binary/` which is not the case in the URL, so Ansible can't find the file and verify the checksum.

Is this expected behavior or a real problem ?

Example Ansible task : 

```yaml
- name: download and install gomplate
  get_url:
    url: "https://github.com/hairyhenderson/gomplate/releases/download/v3.11.3/gomplate_linux-amd64"
    checksum: "sha256:https://github.com/hairyhenderson/gomplate/releases/download/v3.11.3/checksums-v3.11.3_sha256.txt"
    dest: "/usr/local/bin/gomplate"
    backup: true
    owner: root
    group: root
    mode: 0755
  tags: gomplate
```

Extract from https://github.com/hairyhenderson/gomplate/releases/download/v3.11.3/checksums-v3.11.3_sha256.txt : 

```
...
2c67ef580d2416e82dc2ab8f0c30e1bf372dcd3e8511073df9310d91dc3d5f94  bin/gomplate_linux-amd64
...
```

Output of `ansible --version` : 

```
ansible 2.9.27
  ...
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Jan 14 2022, 11:04:20) [GCC 8.5.0 20210514 (Red Hat 8.5.0-7)]
```

When running the Ansible task the obtained error message is : 

```
fatal: [myserver.example.com]: FAILED! => {"changed": false, "msg": "Unable to find a checksum for file 'gomplate_linux-amd64' in 'https://github.com/hairyhenderson/gomplate/releases/download/v3.11.3/checksums-v3.11.3_sha256.txt'"}
```
