### ISSUE TITLE
how do i align the labels and annotations ?

### ISSUE THREAD

**Issue by gabrielfsousa** [hairyhenderson/gomplate#1580]
tmpl
```
{{ range $namespaces := (ds "v").namespaces -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespaces.name }}
  labels:
    {{ ds "l" | data.ToYAML -}}
  annotations:
    {{ ds "l" | data.ToYAML }}
{{ end -}}
```
env 
```
{a: a, b: b, c: c, d: d}
```
result
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: TES
  labels:
    a: a
b: b
c: c
d: d
annotations:
    a: a
b: b
c: c
d: d

```
