### ISSUE TITLE
Keep indentation

### ISSUE THREAD

**Issue by estahn** [hairyhenderson/gomplate#162]
```
foo:
  bar:
    {{ `{"f1": {"f2": 2}}` | json | toYAML }}
```

**Expected Result:**
```
foo:
  bar:
    f1:
      f2: 2
```

**Actual Result:**
```
foo:
  bar:
    f1:
  f2: 2
```

**Comment by hairyhenderson** [comment]
@estahn for this, you want [the `indent` function](https://gomplate.hairyhenderson.ca/functions/general/#indent) - I actually wrote that specifically for dealing with YAML indentation 😉

**Comment by estahn** [comment]
Well, that would result in pretty ugly templates, e.g.

```
spec:
  schedule: "{{ .schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 30
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: app
              image: "123"
              args:
{{ .args | toJSON | indent("              ") }}
```

**Comment by hairyhenderson** [comment]
Yup, I agree, that's not ideal. But there's no way for `gomplate` to know about text outside of the `{{`/`}}` delimiters.

In your specific case, since YAML is a JSON superset, it's probably best to take the approach you seem to have explored in #163 and render that particular value as JSON.

**Comment by estahn** [comment]
Would it be possible to adjust `indent` to something what jinja provides?

http://jinja.pocoo.org/docs/2.9/templates/#indent

>` indent(s, width=4, indentfirst=False)`
> Return a copy of the passed string, each line indented by 4 spaces. The first line is not indented. If you want to change the number of spaces or indent the first line too you can pass additional parameters to the filter:
> 
> `{{ mytext|indent(2, true) }}`
>     indent by two spaces and indent the first line too.

**Comment by hairyhenderson** [comment]
@estahn Just to be clear about what you're asking - are you looking for `indent` to be callable like this?

```console
$ gomplate -i '{{ "foo" | indent 4 }}'
    foo
```

That seems reasonable. Because `indent` already exists, I can't change the existing functionality, but what I _can_ do is overload it so that you can provide an optional width parameter.

Is the `indentfirst` option of jinja's `indent` useful to you? If I were to implement that it'd probably be as a separate function (maybe `strings.IndentAfter` or something like that).

**Comment by estahn** [comment]
It is probably useful otherwise you will need to place the placeholder always at the beginning of the line. 

Example:
```
spec:
  schedule: "{{ .schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 30
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: app
              image: "123"
              args:
                {{ .args | toYAML | indent(16) }}
```

vs

```
spec:
  schedule: "{{ .schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 30
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: app
              image: "123"
              args:
{{ .args | toYAML | indent(16) }}
```
