### ISSUE TITLE
Gomplate not preserving AWS-specific custom YAML tags on merge

### ISSUE THREAD

**Issue by greg-caffeine** [hairyhenderson/gomplate#1997]
I would like to use gomplate to allow overriding and merging of sections of CloudFormation YAML templates with other YAML sections defined in other files by using the gomplate `merge` datasource.  Unfortunately, gomplate drops the AWS-specific YAML tags in the merged output, breaking the template.

Example:

cloudfront_template.yaml:
```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A gomplate test

Parameters:
  MyParameter:
    Type: String

Globals:
  Function:
    Environment:
      Variables:
        MY_PARAMETER: !Ref MyParameter
```

cloudfront_overrides.yaml:
```
Globals:
  Function:
    Environment:
      Variables:
        MY_OTHER_PARAMETER: my_other_value
```

Gomplate Command
`% gomplate -d 'merger=merge:cloudfront_template.yaml|cloudfront_overrides.yaml' -i '{{ include "merger" }}'`

OUTPUT
```
AWSTemplateFormatVersion: 2010-09-09T00:00:00Z
Description: A gomplate test
Globals:
  Function:
    Environment:
      Variables:
        MY_OTHER_PARAMETER: my_other_value
        MY_PARAMETER: MyParameter
Parameters:
  MyParameter:
    Type: String
Transform: AWS::Serverless-2016-10-31
```

Note in the output that `MY_PARAMETER: !Ref MyParameter` has not been preserved and instead has been transformed into `MY_PARAMETER: MyParameter`, losing the `!Ref` tag.

Is there any way to get gomplate to preserve all HTML tags in the output, or to provide a list of tags to preserve?

A list of AWS custom tags can be found [here](https://stackoverflow.com/questions/53470329/aws-sam-yaml-template-unknown-tag-ref).
