### ISSUE TITLE
Cannot install in GitHub Actions using go install

### ISSUE THREAD

**Issue by Cavaler** [hairyhenderson/gomplate#2053]
I'm trying to install gomplate in GHA with the following:

```yaml
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install gomplate
        run: |
          go get github.com/hairyhenderson/gomplate/v4/cmd/gomplate@latest
          gomplate --help
```

But I get an error:

```
Run go install github.com/hairyhenderson/gomplate/v4/cmd/gomplate@latest
go: downloading github.com/hairyhenderson/gomplate v3.5.0+incompatible
go: downloading github.com/hairyhenderson/gomplate/v4 v4.0.0-pre-2
go: github.com/hairyhenderson/gomplate/v4/cmd/gomplate@latest (in github.com/hairyhenderson/gomplate/v4@v4.0.0-pre-2):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

Either this should be fixed in some way, or this installation method should be removed from documentation.
