### ISSUE TITLE
nested template technique?

### ISSUE THREAD

**Issue by f4tq** [hairyhenderson/gomplate#210]
Is there a way to do this?
file data: 
```
---
a: 1
```
template1 data:
```
Welcome to {{.a}
{{ if .a == 1}} 
{{ template "foo" }}
{{ end - }}
```
It seems like `--input-dir` just renders everything unconditionally.  
It seems like `-d foo=template://foo.t` could be used treat conditional (nested) templates as datasources.  Since go templates need names, it fits with the `-d` scheme.  

I ran into trouble with `-d` and the use of a `.t` suffix trying to sniff mime typing so maybe a different switch with nearly identical behavior as `-d` that can be used for `define`ing templates for use in `{{template "foo"}}`...

Is there another way to do it?

Thanks for doing this!

**Comment by hairyhenderson** [comment]
Hi @f4tq - thanks for logging this!

> It seems like `--input-dir` just renders everything unconditionally.

Right - it's intended for use with a directory containing _just_ templates. If you don't want to attempt to render certain files, it's probably best to wrap `gomplate` with a script which can differentiate between the types of files you want to render and those you don't.

> It seems like `-d foo=template://foo.t` could be used treat conditional (nested) templates as datasources. Since go templates need names, it fits with the `-d` scheme.

Interesting! It _does_ seem like it'd be a close fit. Right now, `--datasource`/`-d` is intended for use specifically with the `datasource`/`include` functions, and not `template` (which is a built-in). But I think for this use-case it's probably worth adding that support.

> I ran into trouble with `-d` and the use of a `.t` suffix trying to sniff mime typing ...

What sort of trouble? You _should_ be able to use an arbitrary file as input, then you can use [`include`](https://gomplate.hairyhenderson.ca/functions/data/#include) to include the data as-is. But I'm not sure this would work to define a template.

**Comment by f4tq** [comment]
I [fixed this and more on my fork here](https://github.com/f4tq/gomplate/commit/9b12c6a45b10cc3793ace1c4ec134ba10a6a5418)
### Briefly
- I added `dict` and `slice` functions
- I removed the need for `(datasource "xyz").result.data` constructs but I left them in place
> I did not remove the cache concept nor the `datasource` function but they are un-necessary. I replaces the empty `Context` struct passed to template execution with resolved namespace passed from the cli with actual trees.
- I implemented nested templates

I am under the gun so I pressed on.  If you're willing, I'll submit a PR. 

### Overview
Given a data(source) like:
```data.yaml:
---
azure:
   security:
   - rule: 1
      prioriy: 99
```
You can run `gomplate -d rules=file://data.yaml -i ' my rule priority is: {{ .rules.azure.rules[0].priority}}' `

> No more use of `(datasource "rules").azure.rules[0].priority.

I implemented nested templates too.

To support it, I added a `dict` and `slice` function so that input data keys (from datasources) can be mapped to what nested templates expect.  I called them partials -- alla ruby.  The switch is `--partial-dir`. 
`--partial-dir` takes in snippets that present interfaces in the form of tokens that need replacement. In order to do this, given your cool library, some mapping neededs to take place.  Hence I introdcued `dict` and `slice` to support operations that need repeating & mapping.

To make partials generic & re-usable, you need to be able to map datasource keys to keys partials expect.

So now this works:

```
{{  range slice "MasterA" "MasterB" "ControlA" "ControlB" "ProxyA" "ProxyB" "LoggingA" "LoggingB" "WorkerA" "WorkerB" "Database" "Util"  }}

- apiVersion: "[variables('apiVersionDefault')]"
  location: "[resourceGroup().location]"
  name: "[variables('{{.}}NSGName')]"
  properties:
    securityRules:
    - name: Allow_Jump_Egress_IP
      properties:
        access: Allow
        description: Allow traffic from the jump host public IP
        destinationAddressPrefix: "*"
        destinationPortRange: "22"
        direction: Inbound
        priority: 201
        protocol: "*"
        sourceAddressPrefix: "[variables('JumpSubnetCidr')]"
        sourcePortRange: "*"
  type: Microsoft.Network/networkSecurityGroups
{{ end }}
```

and this works for nesting given a template like `azuredeploy.yaml`:

```
- apiVersion: "[variables('apiVersionDefault')]"
  location: "[resourceGroup().location]"
  name: "[variables('JumpNSGName')]"
  properties:
    securityRules:
{{ template "arm/partials/whitelist.yaml.t" dict "Port" 22 }}
  type: Microsoft.Network/networkSecurityGroups
```
> Notice the use of both `dict` and `slice`. In the latter, whitelist.yaml.t expect `.Port` to be set.  `dict` handles that.

Here is`whitelist.yaml.t`:
```
--snip
    - name: orca_moonbeam_300
      properties:
        access: Allow
        description: Orca/Moonbeam IP, 300
        destinationAddressPrefix: "*"
        destinationPortRange: "{{.Port}}"
        direction: Inbound
        priority: 300
        protocol: "*"
        sourceAddressPrefix: 52.xx.2y2.xxx/32
        sourcePortRange: "*"
--snip--
```

Let me know what you think.  You can pull my fork. 

With these changes,  gomplate is incredibly awesome & useful.  

I've charged into the depths of my project but this could be REALLY useful combined with your datasource concept.
 I'm already down the road, drinking the kool-aid.

Cheers,
Chris
