### ISSUE TITLE
`excludeProcessing` does not obey negative patterns

### ISSUE THREAD

**Issue by orens** [hairyhenderson/gomplate#2208]
Hi. Thanks for this great tool!
I've been trying to use `excludeProcessing` to copy everything **other than** some pattern:
```yaml
inputDir: /gomplate/input
# ...
excludeProcessing:
  - '!*.tmpl'
```
However, all files are being included in the processing (although it is a valid `.gitignore` pattern)

I am trying to copy an entire `inputDir` and only process certain files. In my case, I am renaming the `*.tmpl` files and removing the `tmpl` extension afterwards, using an `outputMap`
Is there any way I can achieve this?
If not, can negative patterns be added to `excludeProcessing`?

Thank you
