### ISSUE TITLE
File datasource not loaded if path starts with `../`

### ISSUE THREAD

**Issue by ItalyPaleAle** [hairyhenderson/gomplate#2230]
I am using gomplate with this configuration:

```yaml
inputDir: "src"
outputDir: "Ev2ServiceArtifactsRoot"
datasources:
  AzureRegions:
    url: "../../../deployment-config/AzureRegions.yaml"
```

If I do `ls "../../../deployment-config/KustoClusters.yaml"`, I see the file, indicating the path is correct

I am getting an error that it can't load the "AzureRegions" data source:

```
16:20:15 ERR  err="renderTemplate: failed to render template src/Ev2Config.json: template: src/Ev2Config.json:19:26: executing \"src/Ev2Config.json\" at <datasource \"AzureRegions\">: error calling datasource: couldn't read datasource 'AzureRegions' (deployment-config/AzureRegions.yaml): open (url: \"/\", name: \"deployment-config/AzureRegions.yaml\"): open Users/alessandro/Code/AAPT-DTMB/src/Infrastructure/Kusto/deployment-config/AzureRegions.yaml: no such file or directory"
```

Note that `/Users/alessandro/Code/AAPT-DTMB/src/Infrastructure/Kusto` is the working directory, so it seems that it is not resolving the `../` at the start of the path
