### ISSUE TITLE
`data.ToYAML` adds an extra newline

### ISSUE THREAD

**Issue by rocketraman** [hairyhenderson/gomplate#231]
Datasource `foo.yaml`:

```yaml
bar: "baz"
```

Template `template.yaml`:

```yaml
k1:
  {{ datasource "foo" | data.ToYAML }}
k2: xxx
```

Output:

```yaml
k1:
  bar: "baz"

k2: xxx
```

Note: whether the newline at the end of the input datasource is present or not makes no difference... and this is a good thing since I could be passing a fragment of the datasource yaml to `data.ToYAML`.

**Comment by hairyhenderson** [comment]
@rocketraman I think this is expected - could you try this instead:

```yaml
k1:
  {{ datasource "foo" | data.ToYAML -}}
k2: xxx
```
