### ISSUE TITLE
Template insertion of yaml inside yaml fails

### ISSUE THREAD

**Issue by rocketraman** [hairyhenderson/gomplate#232]
Say I have a template:

```yaml
foo:
  bar:
    {{ (datasource "foo").bar | data.ToYAML }}
```

with datasource `foo.yaml`

```yaml
bar:
  baz: 1
    barbaz: 1.1
  qux: 2
```

I would expect a nice embedding of my datasource yaml in the template yaml looking like this:

```yaml
foo:
  bar:
    baz: 1
      barbaz: 1.1
    qux: 2
```

However I get this:

```
foo:
  bar:
    2017/11/15 19:41:50 Unable to unmarshal object bar:
  baz: 1
    barbaz: 1.1
  qux: 2
: yaml: line 2: mapping values are not allowed in this context
```

**Comment by hairyhenderson** [comment]
Hi @rocketraman - thanks for logging this issue!

Your `foo.yaml` file doesn't contain valid YAML syntax. Try validating it with a tool like http://www.yamllint.com - you'll see the same error: "mapping values are not allowed in this context at line 3 column 11"

The problem is with the `baz` key. It's assigned a value `1`, but then _also_ assigned a value of `{ "barbaz": 1.1 }` (translated to JSON).

This should work with valid YAML input, so I'll close this for now. Thanks!

**Comment by rocketraman** [comment]
@hairyhenderson Sorry that was an error in my test case. Here is the corrected `foo.yaml`:

```yaml
bar:
  baz:
    barbaz: 1.1
  qux: 2
```

and here is the output after running `gomplate -d foo=foo.yaml -f template.yaml`:

```yaml
foo:
  bar:
    baz:
  barbaz: 1.1
qux: 2
```

You can see that the indentation of the output is completely incorrect -- neither `barbaz` or `qux` are indented correctly.

**Comment by hairyhenderson** [comment]
Ah. That makes more sense. This is expected - the function has no idea that its contained within a YAML document already, which is why the [`strings.Indent`](https://gomplate.hairyhenderson.ca/functions/strings/#strings-indent) function exists. Try this as your `template.yml` instead:

```yml
foo:
  bar:
{{ (datasource "foo").bar | data.ToYAML | strings.Indent 4 -}}
```

```console
$ gomplate -d foo.yml -f template.yml
foo:
  bar:
    baz:
      barbaz: 1.1
    qux: 2
```
