### ISSUE TITLE
Provide alternative to trimSpace for reading a multi-line file.

### ISSUE THREAD

**Issue by seastco** [hairyhenderson/gomplate#2375]
I am using gomplate to render my cloud-config. I am adding `indent 6` but I don't want to indent the first line in addition to the indentation I'm adding myself. It seems like my two options are:

```
#cloud-config
write_files:
  - content: |
      {{ file.Read "./scripts/common.sh" | indent 6 | trimSpace }}
    path: "/usr/local/bin/cloudinit/common.sh"
    permissions: '0755'
  - content: |
      {{ file.Read "./scripts/install-kubectl.sh" | indent 6 | trimSpace }}
    path: "/usr/local/bin/cloudinit/install-kubectl.sh"
    permissions: '0755'
  - content: |
      {{ file.Read "./scripts/install-docker.sh" | indent 6 | trimSpace }}
    path: "/usr/local/bin/cloudinit/install-docker.sh"
    permissions: '0755'
```
or

```
#cloud-config
write_files:
  - content: |
{{ file.Read "./scripts/common.sh" | indent 6 }}
    path: "/usr/local/bin/cloudinit/common.sh"
    permissions: '0755'
  - content: |
{{ file.Read "./scripts/install-kubectl.sh" | indent 6 }}
    path: "/usr/local/bin/cloudinit/install-kubectl.sh"
    permissions: '0755'
  - content: |
{{ file.Read "./scripts/install-docker.sh" | indent 6 }}
    path: "/usr/local/bin/cloudinit/install-docker.sh"
    permissions: '0755'
```
Is there anything better or more intuitive? Something like sprigs [nindent](https://masterminds.github.io/sprig/strings.html) would be nice to have here.
