### ISSUE TITLE
Question: Combining file datasource with ENV in template

### ISSUE THREAD

**Issue by sh33pz0r** [hairyhenderson/gomplate#460]
I have a specific use case where a couple of components want to use the same data source `conf` yaml file as follows:

```
backend:
  master_server: 1.1.1.1
  s3_bucket: abc

frontend:
  master_server: 2.2.2.2
  s3_bucket: xyz
```

my input template:
```
master.server = {{ (ds "conf").master_server }}
bucket = {{ (ds "conf").s3_bucket }}
```

obviously that will fail, is there a way to dynamically evaluate lets say an ENV VAR to combine it with the datasource? as in `{{ (ds "conf").Env.SERVERTYPE.s3_bucket }}` so gomplate will choose the right values for the specific component. if there are other suggestions, i can try.
thanks
