### ISSUE TITLE
Feature request: jsonpath like query functionality

### ISSUE THREAD

**Issue by rayjlinden** [hairyhenderson/gomplate#517]
As I'm developing more complex data sources I'm using with gomplate - I'm finding it would be nice to have functionality like jq or jsonpath.  For example, I'd like to be able to do something like:

```
{{- range $service :=  (jsonpath $data "$.repos.*.services.*~")  }}
{{ $service }}
{{- end }}
```

This would return a list of "accounts-api", "accounts-rpc", "pro-service", etc. for a data set like this:
```
repos:
  accounts:
    services:
      accounts-api:
      accounts-rpc:
        Expose: "4433"
  utils-repo:
  plans:
    services:
      pro-service:
      other-service:
```

https://godoc.org/k8s.io/client-go/util/jsonpath

Probably going to be interesting issues with the syntax of JsonPath vs. GoTemplates that might make this much harder than it seems like it would be.  But boy the power of something like this sure would make some things much easier.  (Currently, I'm using jq to build a new data source from the main one.  This makes the templates simple enough - but makes calling the templates a bit more complicated.)
