### ISSUE TITLE
Feature request: ability to remove entries from dict

### ISSUE THREAD

**Issue by mook-as** [hairyhenderson/gomplate#825]
Currently, when given a `dict`, it is possible to add a key to it via [`coll.Merge`](https://docs.gomplate.ca/functions/coll/#coll-merge).  However, there appears to be no way to unset an entry in a `dict`.

(The syntax for using `merge` is rather complicated, but at least it's possible, I guess?)

This would be equivalent to sprig's [`unset`](http://masterminds.github.io/sprig/dicts.html#unset).

**Comment by hairyhenderson** [comment]
Hi @mook-as, thanks for logging this!

I considered an `unset` type function, and even started working on one, but there didn't seem to be an actual use-case.

Can you let me know a bit about why you'd like to be able to delete entries from `dict`s? I want to make sure I understand your use-case before implementing it.

**Comment by mook-as** [comment]
Hi!

I'm basically using gomplate to generate (YAML) config files sort of a shortcut: if `a` is set, generate (merge with existing) configs in `b.c`, `b.d`, `e.f`, etc., and then unset `a` to ensure it doesn't interfere with the actual config files.  Currently I'm working around things using [`yq`](https://mikefarah.gitbook.io/yq/), but that is somewhat unsatisfying.

**Comment by hairyhenderson** [comment]
@mook-as thanks - are you able to post your templates & commands (both `gomplate` and `yq` commands) so I can get a better idea of what you're going?

**Comment by mook-as** [comment]
I can post some of that, sure.

I have, at this point, a config file, and then a collection of gomplate template files (`10-foo.yaml.tmpl`, `20-bar.yaml.tmpl`, etc.) that I apply serially to modify the config in-place (well, into temporary files because I can't figure out how to make gomplate render datasources as if they were templates).  One such template is:

<details>
<summary><code>90-system-domain-values.yaml.tmpl</code></summary>

```yaml
{{- if eq .kube.type "kind" }}

# External cluster access is not possible
system_domain: example.com

services:
  router:
    type: ClusterIP
    clusterIP: 10.104.255.1
  ssh-proxy:
    type: ClusterIP
    clusterIP: 10.104.255.2
  tcp-router:
    type: ClusterIP
    clusterIP: 10.104.255.3

{{- else if eq .kube.type "minikube" }}

{{- if .features.ingress.enabled }}

# Ingress configs are in 50-ingress.yaml.tmpl

{{- else }}

system_domain: {{ .kube.ip }}.{{ index .kube "domain-suffix" }}

services:
  router:
    type: ClusterIP
    externalIPs: [{{ .kube.ip }}]
  ssh-proxy:
    type: ClusterIP
    externalIPs: [{{ .kube.ip }}]
  tcp-router:
    type: ClusterIP
    externalIPs: [{{ .kube.ip }}]

{{- end }}

{{- else }}
{{- fail "unknown cluster type" }}
{{- end }}
```
</details>

(That is, I have values for `system_domain` and `services`, based on what sort of cluster I'm deploying to — kind or minikube; and if it's minikube, based on if I have ingress enabled.)

Here, `.kube.type` is an internal tracking thing I'm doing for my (local) deploy script, and shouldn't exist in the final output.  So I'm doing things like:

```bash
    for i in $(echo ./*.yaml.tmpl | sort -n) ; do
        CURRENT="${i}"
        gomplate \
            --context ".=file://${OUTPUT}" \
            --file "${i}" \
            > "${OUTPUT}.temp.yaml"
        gomplate \
            --datasource "output=file://${OUTPUT}" \
            --datasource "rendered=file://${OUTPUT}.temp.yaml" \
            --context ".=merge:output|rendered" \
            --in '{{ . | toYAML }}' \
        > "${OUTPUT}.new"
        rm -f "${OUTPUT}.temp.yaml"
        mv "${OUTPUT}.new" "${OUTPUT}"
    done
```

And for the deletion part, that lives a bit outside (because I can't have it live in the template files that consume these flags):
```bash
DELETIONS=(
    kube["domain-suffix"]
    kube.ip
    kube.type
)
for deletion in "${DELETIONS[@]}" ; do
    yq delete --inplace "${OUTPUT}" "${deletion}"
done
```
