### ISSUE TITLE
Feature request: datasource variable expression

### ISSUE THREAD

**Issue by RecuencoJones** [hairyhenderson/gomplate#867]
I'm unsure this is currently possible, but for some use case we are using aws+sm datasource which returns a JSON string that needs to be parsed before we can start extracting values out of it.

It somewhat looked like this:

```yaml
# secrets/file1.yaml
kind: Secret
apiVersion: v1
metadata:
  name: file1
data:
  key: '{{ (ds "aws" "kubernetes-secrets" | json).KeyValue | base64.Encode }}'
  secret: '{{ (ds "aws" "kubernetes-secrets" | json).KeySecret | base64.Encode }}'
```
```yaml
# secrets/file2.yaml
kind: Secret
apiVersion: v1
metadata:
  name: file2
data:
  key: '{{ (ds "aws" "kubernetes-secrets" | json).AnotherKeyValue | base64.Encode }}'
  secret: '{{ (ds "aws" "kubernetes-secrets" | json).AnotherKeySecret | base64.Encode }}'
```

I moved this to a variable to not repeat myself within the file, so:

```yaml
# secrets/file1.yaml
{{ $secrets := ds "aws" "kubernetes-secrets" | json }}
kind: Secret
apiVersion: v1
metadata:
  name: file1
data:
  key: '{{ $secrets.KeyValue | base64.Encode }}'
  secret: '{{ $secrets.KeySecret | base64.Encode }}'
```
```yaml
# secrets/file2.yaml
{{ $secrets := ds "aws" "kubernetes-secrets" | json }}
kind: Secret
apiVersion: v1
metadata:
  name: file2
data:
  key: '{{ $secrets.AnotherKeyValue | base64.Encode }}'
  secret: '{{ $secrets.AnotherKeySecret | base64.Encode }}'
```

However, I'm still repeating the variable declaration through files, it would be great if instead I could define it as a datasource:

```
gomplate \
  --input-dir secrets \
  -d 'aws=aws+sm:' \
  -d '$secrets=var: ds "aws" "kubernetes-secrets" | json'
```

Maybe should be a different flag instead of datasource as it won't have a url schema, so could be:

```
gomplate \
  --input-dir secrets \
  -d 'aws=aws+sm:' \
  --declare '$secrets := ds "aws" "kubernetes-secrets" | json'
```

**Comment by hairyhenderson** [comment]
Thanks for this @RecuencoJones. I don't think it'll be possible to declare variables on the commandline like that (it's not possible to declare those with Go templating), however this is what the `-c`/`--context` feature is for.

Also, I don't think the JSON parsing should be necessary inside the template - you can override the MIME type with the `?type=` query parameter instead on the commandline, and then gomplate will automatically parse the data as JSON.

So maybe try something like:

_secrets/file1.yaml:_
```yaml
# secrets/file1.yaml
kind: Secret
apiVersion: v1
metadata:
  name: file1
data:
  key: '{{ .kubesecrets.KeyValue | base64.Encode }}'
  secret: '{{ .kubesecrets.KeySecret | base64.Encode }}'
```

And you'd render these with this command:

```console
gomplate --input-dir secrets \
  --context 'kubesecrets=aws+sm:///kubernetes-secrets?type=application/json'
```

See https://docs.gomplate.ca/usage/#context-c for docs on `--context`, and https://docs.gomplate.ca/datasources/#overriding-mime-types for docs on overriding the MIME type.

Let me know if this helps!
